version: 1.0.0.{build}
configuration: Release
platform: Any CPU
build:
  project: KeepAwake.sln
  verbosity: normal
after_build:
- cmd: '"packages\NSIS.2.51\tools\makensis.exe" "installer\KeepAwake.nsi"'
artifacts:
- path: Installer\KeepAwake_setup.exe
deploy:
- provider: GitHub
  auth_token:
    secure: kii7ae53CEEJdJ6lVs2I3UfPfKM0DvQgto8nxRDlaqfxM2UTbUtLQ0agrzu3pHDP